# Generated by Django 5.2.17 on 2026-09-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackcard',
            options={},
        ),
    ]
