# Generated by Django 5.2.17 on 2026-09-07 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedbackcard_options'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcard',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='topics.topic'),
        ),
    ]
